config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  get '/about', to: 'home#about'

  resource :user, only: [:index] do
    resources :posts,only: [:index, :show, :edit, :update, :destroy],
              as: 'manage_posts',
              controller: 'manage_posts'
  end
  resources :posts, only: [:show, :new, :create] do
    resources :comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates :commenter,  presence: true
  validates :comment, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  mount_uploader :postimage, PostimageUploader

  # draft(0): 下書き
  # published(1) : 通常状態
  # archived(-1) : 一覧に表示されなくなる（アーカイブ）
  enum status: {draft:0, published:1, archived:-1 }

  validates :title,  presence: true
  validates :content, presence: true
  validates :status, presence: true, inclusion: {in: Post.statuses.keys}

  # postimage の validation(size) は uploaders/postimage_uploader.rb
    # def size_range
    #   1..5.megabytes
    # end
  # で行う。数字を変更する場合はこれを変更する。

  # publishedがenumでscopeが用意はされてますが、学習のために残しています。
  # scope :published, -> { where(status: 1) }

end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :login
  has_many :posts, dependent: :destroy


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, authentication_keys: [:login]

  validates :username, presence: :true, uniqueness: { case_sensitive: false },
            length: { in: 2..20 },
            format: { with: /^[a-zA-Z0-9_]*$/,  multiline: true}



  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { value: login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  # def login=(login)
  #   @login = login
  # end
  #
  # def login
  #   @login || self.username || self.email
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
      devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
      devise_parameter_sanitizer.permit :account_update, keys: added_attrs
      # devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:destroy]

  def create
    @user = current_user
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    if @comment.valid?
      flash[:success] = "コメント完了"
      redirect_to post_path(@post)
    else
     flash[:danger] = "内容にエラーがあります"
     # @post = Post.find(params[:post_id])
     @comment = Comment.new
     render 'posts/show'
    end
  end

  #   @post = Post.find(params[:post_id])
  #   @comment = @post.comments.build(comment_params)
  #   if @comment.save
  #       flash.now[:success] = "コメント完了"
  #       redirect_to post_path(@post)
  #   else
  #     flash.now[:danger] = "内容にエラーがあります"
  #     # @post = Post.find(params[:post_id])
  #     render 'posts/show'
  #   end
  # end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    flash[:success] = "コメント削除完了"
    redirect_to post_path(@post)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :comment)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    # 公開済postのみ取得(published)
    @post = Post.all.published.includes(:user).order('created_at DESC').page params[:page]
    # @post = Post.all.order('created_at DESC')
    @user = current_user if user_signed_in?
  end

  def about
    @user = current_user if user_signed_in?
    render 'layouts/about'
  end
end

app/controllers/manage_posts_controller.rb
class ManagePostsController < ApplicationController
  before_action :authenticate_user!
  def index
      @user = current_user
      # html と csv で分ける
      respond_to do |format|
        format.html do
          @user_post = current_user.posts.
                       order('created_at DESC').page params[:page]
        end
        format.csv do
          @user_post_csv = current_user.posts
          send_data render_to_string, filename: "user_posts.csv", type: :csv
        end
      end
  end

  def show
    @user = current_user
    @user_post = @user.posts.find(params[:id])
  end

  def edit
    @user = current_user
    @user_post = current_user.posts.find(params[:id])
  end

  def update
    @user = current_user
    @user_post = Post.find(params[:id])
    if  @user_post.update_attributes(post_params)
      redirect_to user_manage_posts_path, flash: {success: '編集完了'}
    else
      render 'edit'
    end
  end

  def destroy
    user_post = Post.find(params[:id])
    user_post.destroy
    flash[:success] = "記事を削除しました"
    redirect_to user_manage_posts_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :content, :postimage, :postimage_cache, :status)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include ActionView::Helpers::UrlHelper
  before_action :authenticate_user!, only: [:create, :new, :destroy]

  def new
    @user = current_user
    @post = Post.new
    @comment = Comment.new
  end

  def create
    @user = current_user
    @post = current_user.posts.build(post_params)
    if @post.save
      flash.now[:success] = "投稿完了しました！！"
      redirect_to root_path
    else
      flash.now[:danger] = "エラーがあるため投稿できませんでした。"
      @commnet = Comment.new
      render :new
    end
  end

  def show
    @user = current_user
    @post = Post.find(params[:id])
    # @post = Post.includes(:user).find(params[:id])
    @comment = Comment.new
  end

  private
    def post_params
      params.require(:post).permit(:title, :content, :postimage, :postimage_cache, :status)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title ='')
    title_name = '自力ブログ作成'
    if page_title.empty?
      title_name
    else
      page_title + " " + title_name
    end
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/manage_posts_helper.rb
module ManagePostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_new.html.erb
<h3>コメントを書く</h3>
<%= form_for([@post, @comment]) do |f| %>
  <%= render 'shared/error_messages', obj: @comment %>

  <p><%= f.label :commenter %></p>
  <%= f.text_field :commenter %>

  <p><%= f.label :comment %></p>
  <%= f.text_area :comment %>

  <p><%= f.submit %></p>
<% end %>

app/views/comments/_show.html.erb
<h3>コメント</h3>

<% @post.comments.each do |body| %>
    <p>名前 : <%= body.commenter %></p>
    <p>コメント : <%= body.comment %></p>
    <!-- ログインをしていれば「削除」linkを表示 -->
    <% if user_signed_in? %>
      <p><%= link_to t('delete'), [@post,body], method: :delete %></p>
    <% end %>
      <!-- post_comment_path(@post, @post.comments[:id]) -->
<% end %>

app/views/home/index.html.erb
<h1>投稿一覧表示</h1><br><hr>
<% @post.each do |post| %>
<!-- published の記事のみ表示 published(公開) -->
    <h2><%= link_to post.title, post_path(post.id)  %></h2>
    <p>本文　：　<%= post.content%></p>
    <p><%= post.created_at.strftime('%Y-%m-%d %H:%M:%S') %></p>
    <p><%= image_tag(post.postimage.thumb.url) if post.postimage?%></p>
    <p><em>ユーザー名：<%= post.user.username %> </em></p>
    <p><%= time_ago_in_words(post.created_at)%></p>
    <br><hr>
<% end %>

<%= paginate @post %>

app/views/layouts/_header.html.erb
<div id="top-title">
  <%= link_to "自力ブログ", root_path, id: "logo" %>
</div>
<header class="navbar navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav">

        <li><%= link_to t('home'), root_path %></li>
        <li><%= link_to  t('about'), about_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t('post diary'), new_post_path %></li>

        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t('My page') %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t('posted diary'), user_manage_posts_path %></li>
              <!-- <li><%= link_to "Settings", '#' %></li> -->
            </ul>
          </li>
          <li><%= link_to t('log out'), destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to t('log in'), user_session_path %></li>
          <li><%= link_to t('signup'), new_user_registration_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/about.html.erb
<h1>About</h1>
<p>ブログについて</p>
<p>チュートリアルを参考に作ってみたブログ</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>

    <!-- ユーザー名表示 -->
    <%= @user.username if user_signed_in? %>
  <div class="container">
    <%= yield %>
  </div>
  <%= debug(params) if Rails.env.development? %>

  </body>

app/views/manage_posts/_form.html.erb
<%= render 'shared/error_messages', obj: @post %>

<%= form_for(@post) do |f| %>
  <div class="field">
      <%= f.label :title %>
    <p>
      <%= f.text_field :title, autofocus: true %>
    </p>
  </div>

  <div class="field">
      <%= f.label :content %>
    <p>
      <%= f.text_area :content %>
    </p>
  </div>

  <div class="field">
      <%= f.label :postimage %>
    <p>
      <%= image_tag(@post.postimage.thumb_error.url) if @post.postimage? %>
      <%= f.file_field :postimage %>
      <%= f.hidden_field :postimage_cache %>
    </p>
  </div>

  <div class="field">
      <%= f.label :status %>
    <p>
      <%= f.select :status, Post.statuses.keys.map{|k| [Post.statuses_i18n[k], k]} %>
    </p>
  </div>

  <div class="actions">
    <%= f.submit yield(:button_text) %>
  </div>
<% end %>

app/views/manage_posts/edit.html.erb
<% provide(:button_text, '編集完了') %>
<h1>編集画面</h1>

<%= render 'shared/error_messages', obj: @user_post %>

<%= form_for @user_post, url: user_manage_post_path do |f| %>
  <div class="field">
      <%= f.label :title %>
    <p>
      <%= f.text_field :title, autofocus: true %>
    </p>
  </div>

  <div class="field">
      <%= f.label :content %>
    <p>
      <%= f.text_area :content %>
    </p>
  </div>

  <div class="field">
      <%= f.label :postimage %>
    <p>
      <%= image_tag(@user_post.postimage.thumb_error.url) if @user_post.postimage? %>
      <%= f.file_field :postimage %>
      <%= f.hidden_field :postimage_cache %>
    </p>
  </div>

  <div class="field">
      <%= f.label :status %>
    <p>
      <%= f.select :status, Post.statuses.keys.map{|k| [Post.statuses_i18n[k], k]} %>
    </p>
  </div>

  <div class="actions">
    <%= f.submit yield(:button_text) %>
  </div>
<% end %>

app/views/manage_posts/index.html.erb
<!-- ログインをしているユーザーの記事のみ表示 -->
<h1><%= @user.username %> の一覧</h1><hr>
<%= link_to 'csv出力', user_manage_posts_path(format: :csv), class: 'btn btn-default' %>
<% @user_post.each do |post| %>
    <h2><%= link_to post.title, user_manage_post_path(post.id)  %></h2>
    <p>本文　：　<%= post.content%></p>
    <p><%= post.created_at.strftime('%Y-%m-%d %H:%M:%S') %></p>
    <p><%= image_tag(post.postimage.thumb.url) if post.postimage?%></p>
    <p><%= time_ago_in_words(post.created_at)%></p>
    <p>状態 : <%= post.status_i18n %></p>
    <p><%= link_to t('edit'), edit_user_manage_post_path(post) %></p>
    <p><%= link_to t('delete'), user_manage_post_path(post), method: :delete %></p>
    <br><hr>
<% end %>

<%= paginate @user_post %>

app/views/manage_posts/show.html.erb
<h1><%= @user_post.title %></h1>
<p><%= @user_post.content %></p>
<p><%= @user_post.created_at.strftime('%Y-%m-%d %H:%M:%S') %></p>
<p><%= @user_post.user.username %></p>
<p><%= image_tag(@user_post.postimage_url) if @user_post.postimage?%></p>
<p><%= link_to t('edit'), edit_user_manage_post_path(@user_post) %></p>
<p><%= link_to t('delete'), user_manage_post_path(@user_post), method: :delete %></p>

app/views/posts/new.html.erb
<% provide(:button_text, '投稿') %>
<h1>日記投稿</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.content %></p>
<p><%= @post.created_at.strftime('%Y-%m-%d %H:%M:%S') %></p>
<p><%= @post.user.username %></p>
<p><%= image_tag(@post.postimage_url) if @post.postimage?%></p>
<hr>

<%= render 'comments/show' %>
<%= render 'comments/new' %>

<!-- 「コメントを書く」と「表示」を逆にしてeachで回すと「表示」側に空の一覧が作られる -->

app/views/shared/_error_messages.html.erb
<% if obj.errors.any? %>
    <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
<% end %>